apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reto-app
  namespace: {{ .Values.argocdNamespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.repoURL | quote }}
    targetRevision: {{ .Values.targetRevision | quote }}
    path: {{ .Values.path | quote }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.destinationNamespace }}
  syncPolicy:
    automated:
      prune: true       # remove resources deleted from Git
      selfHeal: true    # revert out-of-band kubectl changes back to Git
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
